# Generated by Django 4.1 on 2022-08-27 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ATMCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('pin', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=35)),
                ('card_status', models.CharField(choices=[('active', 'active'), ('deactivated', 'deactivated')], default='deactivated', max_length=11)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('expire_date', models.DateField(default=datetime.datetime(2026, 8, 26, 21, 30, 53, 465571, tzinfo=datetime.timezone.utc))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atm_account', to='account.bankaccount', verbose_name='bank account')),
            ],
        ),
    ]
