# Generated by Django 4.1 on 2022-08-27 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcard',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2026, 8, 26, 21, 31, 5, 247640, tzinfo=datetime.timezone.utc)),
        ),
    ]
