# Generated by Django 4.1 on 2022-08-27 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atm', '0002_alter_atmtransaction_expiredat_and_more'),
        ('account', '0003_alter_atmcard_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_validate', models.BooleanField(default=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('expireAt', models.DateTimeField(default=datetime.datetime(2022, 8, 27, 21, 34, 10, 962583, tzinfo=datetime.timezone.utc))),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atm.atm')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.atmcard')),
            ],
        ),
    ]
