# Generated by Django 4.1 on 2022-08-27 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 21, 50, 58, 26685, tzinfo=datetime.timezone.utc)),
        ),
    ]
