# Generated by Django 4.1 on 2022-08-27 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_token', '0002_alter_cardtoken_expireat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='expireAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 5, 8, 807777, tzinfo=datetime.timezone.utc)),
        ),
    ]
