# Generated by Django 4.1 on 2022-08-27 21:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_atmcard_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=55)),
                ('code', models.IntegerField(default=0)),
                ('atm_code', models.CharField(default='mycode', max_length=65)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(2000000)])),
                ('in_cash', models.JSONField(default={'100': 0, '200': 0, '2000': 0, '500': 0})),
            ],
        ),
        migrations.CreateModel(
            name='ATMTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=1)),
                ('transaction_id', models.CharField(default='08/27/202221:31:05', editable=False, max_length=24, unique=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(100)])),
                ('success', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('in_cash', models.JSONField(default={'100': 0, '200': 0, '2000': 0, '500': 0})),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('expiredAt', models.DateTimeField(default=datetime.datetime(2022, 8, 27, 21, 36, 5, 248317, tzinfo=datetime.timezone.utc))),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atm_transactions', to='atm.atm')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_transactions', to='account.atmcard')),
            ],
        ),
    ]
