# Generated by Django 4.1 on 2022-08-27 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmtransaction',
            name='expiredAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 21, 36, 10, 962279, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atmtransaction',
            name='transaction_id',
            field=models.CharField(default='08/27/202221:31:10', editable=False, max_length=24, unique=True),
        ),
    ]
