# Generated by Django 4.1 on 2022-08-27 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0003_alter_atmtransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmtransaction',
            name='expiredAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 22, 7, 8, 807452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atmtransaction',
            name='transaction_id',
            field=models.CharField(default='074e4b38-f7aa-4cab-86af-89c9e55c85ee', editable=False, max_length=24, unique=True),
        ),
    ]
